_base_: base.yaml 
# inherits from base.yaml overwriting all the parameters following this line if they exist

# Data Splitting
data_splitting:
  random_seed: 42
  # num_folds: 7  # Changed from base

# Data Loading
data_loading:
  # batch_size: 64  # Custom batch size for DenseNet
  # num_workers: 4  # Increased workers

model:
  model_name: "Densenet169"  # Specific model name
  library: "monai"  # Using monai for 4 channels support can use also monai
# Training
training:
  num_epochs: 210
  early_stopping_patience: 35
  # mixup_alpha: 0
  transfer_learning: false
  freezed_layerIndex: null

# Optimizer
optimizer:
  learning_rate: 2e-4  # Custom learning rate
  optimizer_name: "AdamW"  # Changed optimizer
  weight_decay: 1e-4
  patience: 25

# data_augmentation:
#   use_color_transforms: false